import { describe, expect, it } from "vitest";
import { filterOutAutoGeneratedZooms, isAutoGeneratedZoom, type ZoomRegion } from "./types";

function zoom(id: string, source?: ZoomRegion["source"]): ZoomRegion {
	return {
		id,
		startMs: 0,
		endMs: 1_000,
		depth: 2,
		focus: { cx: 0.5, cy: 0.5 },
		mode: "auto",
		source,
	};
}

describe("auto-generated zoom detection", () => {
	it('treats only source="auto" as auto-generated, not mode', () => {
		// Hand-placed zooms default to mode: "auto"; that must never count as auto.
		expect(isAutoGeneratedZoom({ source: "auto" })).toBe(true);
		expect(isAutoGeneratedZoom({ source: "manual" })).toBe(false);
		expect(isAutoGeneratedZoom({})).toBe(false);
	});

	it("keeps manual zooms while removing every auto suggestion", () => {
		const autoA = zoom("auto-a", "auto");
		const autoB = zoom("auto-b", "auto");
		const manual = zoom("manual-a", "manual");
		const legacy = zoom("legacy");

		const next = filterOutAutoGeneratedZooms([autoA, manual, autoB, legacy]);

		expect(next.map((region) => region.id)).toEqual(["manual-a", "legacy"]);
	});

	it("returns the same array instance when there is nothing to delete", () => {
		const regions = [zoom("manual-a", "manual"), zoom("legacy")];
		expect(filterOutAutoGeneratedZooms(regions)).toBe(regions);
	});
});
